Enable OpenCL distro feature
ERROR: Nothing RPROVIDES 'clinfo' (but /meta-sparrow-hawk/recipes-graphics/packagegroups/packagegroup-renesas-graphics.bb RDEPENDS on or otherwise requires it)
clinfo was skipped: using DISTRO 'poky', which is missing required DISTRO_FEATURES: 'opencl'

Signed-off-by: Anh Nguyen <anh.nguyen.pv@renesas.com>